services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Правильный путь в контейнере
    networks:
      - monitoring
    extra_hosts:  # Добавлено для Windows
      - "host.docker.internal:host-gateway"
  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana  # Стандартный путь Grafana
    networks:
      - monitoring
    depends_on:
      - prometheus

  elasticsearch:
    image: elasticsearch:8.11.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node  # Для одиночного узла
      - xpack.security.enabled=false  # Отключаем безопасность для простоты
    networks:
      - monitoring

  logstash:
    image: logstash:8.11.0
    ports:
      - "5000:5000"  # Порт для TCP-входа от приложения
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Для Windows/Mac

  kibana:
    image: kibana:8.11.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - monitoring

networks:
  monitoring:

volumes:
  grafana_data:
